# Main CI workflow for new PRs
name: CI

on:
  pull_request:
    branches: [master]

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout and lint commits
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        continue-on-error: true

  code-formatting-and-linting:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code in the pull request
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # Install npm dependencies for Prettier and Jest
      - name: 'Install npm dependencies'
        run: npm install

      # Prettier formatting
      - name: 'Code formatting verification with Prettier'
        run: npm run prettier:verify

      # ESlint
      - name: 'Lint Lightning Web Components'
        run: npm run lint:lwc

      # Unit tests
      - name: 'Unit test Lightning Web Components'
        run: npm run test:unit:coverage

      # Install PMD
      - name: Install PMD
        run: wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.45.0/pmd-bin-6.45.0.zip && unzip pmd-bin-6.45.0.zip

      # Execute PMD
      - name: Execute PMD
        run: pmd-bin-6.45.0/bin/run.sh pmd --minimum-priority 2 -d force-app -R apex-ruleset.xml -f text -l apex

  scratch-org-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    needs: code-formatting-and-linting
    steps:
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      # Checkout the code in the pull request
      - name: Checkout
        uses: actions/checkout@v3

      # Store secret for dev hub
      - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'

      # Authenticate dev hub
      - name: 'Authenticate Dev Hub'
        run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'

      # Create scratch org
      - name: 'Create scratch org'
        run: 'sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1'

      # Deploy source to scratch org
      - name: 'Push source to scratch org'
        run: 'sfdx force:source:push'

      # Run Apex tests in scratch org
      - name: 'Run Apex tests'
        run: npm run test:apex:coverage

      # Housekeeping
      - name: 'Delete scratch org'
        if: always()
        run: 'sfdx force:org:delete -p -u scratch-org'
